여러번 실행할 수 있는 문제 해결

diff --git a/Operating System/macOS/Public/UnrealLauncher.app/Contents/MacOS/UnrealLauncher b/Operating System/macOS/Public/UnrealLauncher.app/Contents/MacOS/UnrealLauncher
--- a/Operating System/macOS/Public/UnrealLauncher.app/Contents/MacOS/UnrealLauncher
+++ b/Operating System/macOS/Public/UnrealLauncher.app/Contents/MacOS/UnrealLauncher
@@ -10,14 +10,24 @@ function logcat_append() {
     echo -e "$1" >> "$debugOutput"
 }
 
+function cleanup_process() {
+    if [ -r ~/Library/Application\ Support/Epic/UnrealLauncher/newagent.lock ]; then
+        rm ~/Library/Application\ Support/Epic/UnrealLauncher/newagent.lock
+        logcat_append "Successfully removed lock file."
+    else
+        logcat_append "Unable to remove lock file. no such file or directory."
+    fi
+    logcat_append "UnrealLauncher exited at $(date).\n"
+    exit $1
+}
+
 function interrupt_catch() {
     logcat_append "UnrealLauncher detected interrupt. Checking some requirements for processing interrupt."
     pgrep EpicGamesLauncher &> /dev/null && pgrep UnrealEditor &> /dev/null
     if [ $? == 0 ]; then
         logcat_append "The Epic Games Launcher and UnrealEditor was exited recently. UnrealEditor.dmg volume will now ejected."
         diskutil eject $(df -h | grep UnrealEditor | awk '{ print $1 }') >> "$debugOutput" 2>&1
-        logcat_append "UnrealLauncher exited at $(date).\n"
-        exit 0
+        cleanup_process 0
     else
         logcat_append "UnrealEditor does not ejected successfully. Please see the output above."
         logcat_append "Unable to eject UnrealEditor.dmg disk image due to EpicGameLauncher and UnrealEditor is still running."
@@ -26,6 +36,11 @@ function interrupt_catch() {
         return
     fi
 }
+
+if [ -r ~/Library/Application\ Support/Epic/UnrealLauncher/newagent.lock ]; then
+    echo "error: Unable to launch new agent. This app already running."
+    exit 1
+fi
 
 if [ -d ~/Library/Logs/Unreal\ Engine/UnrealLauncher ]; then
     logcat_append "UnrealLauncher was started at $(date)..."
@@ -41,12 +56,27 @@ else
     fi
 fi
 
+if [ -d ~/Library/Application\ Support/Epic/UnrealLauncher ]; then
+    logcat_append "Successfully created lock file."
+    touch ~/Library/Application\ Support/Epic/UnrealLauncher/newagent.lock
+else
+    mkdir ~/Library/Application\ Support/Epic/UnrealLauncher
+    if [ $? != 0 ]; then
+        logcat_append "Unable to create $HOME/Library/Application Support/Epic/UnrealLauncher/newagent.lock: Please check your permission.\n"
+        osascript -e 'tell app "System Events" to display alert "에이젼트 잠금을 적용할 수 없어 계속 진행할 수 없습니다."'
+        exit 1
+    else
+        logcat_append "Successfully created lock file."
+        touch ~/Library/Application\ Support/Epic/UnrealLauncher/newagent.lock
+    fi
+fi
+
 targetDir="$(echo $0 | sed "s/\/UnrealLauncher$//g")"
 cd "$targetDir" >> "$debugOutput" 2>&1
 if [ $? != 0 ]; then
     logcat_append "Unable to locate $targetDir. Aborting.\n"
     osascript -e 'tell app "System Events" to display alert "프로그램 현재 위치에 접근할 수 없어 실행할 수 없습니다. "'
-    exit 1
+    cleanup_process 1
 else
     logcat_append "Current working directory: "
     pwd >> "$debugOutput" 2>&1
@@ -63,12 +93,12 @@ elif [ -d /Volumes/External -a -r /Volumes/External/Applications/Epic\ Games/Unr
     else
         logcat_append "Unable to mount /Volumes/External/Applications/Epic Games/UnrealEditor.dmg disk image. Please check your permission.\n"
         osascript -e 'tell app "System Events" to display alert "UnrealEditor을(를) 마운트 할 수 없습니다. 디스크 쓰기 권한을 확인해 주세요."'
-        exit 1
+        cleanup_process 1
     fi
 else
     logcat_append "Unable to locate UnrealEditor.dmg. Exiting.\n"
     osascript -e 'tell app "System Events" to display alert "External 디스크가 감지되지 않아 UnrealEditor을(를) 마운트할 수 없습니다."'
-    exit 1
+    cleanup_process 1
 fi
 
 if [ -x /Applications/Epic\ Games\ Launcher.app ]; then
@@ -76,7 +106,7 @@ if [ -x /Applications/Epic\ Games\ Launcher.app ]; then
     logcat_append "Succesfully launched Epic Games Launcher.app."
 else
     logcat_append "Unable to execute Epic Games Launcher.app: no such file or directory.\n"
-    exit 1
+    cleanup_process 1
 fi
 
 while : ; do
@@ -112,11 +142,9 @@ while : ; do
             osascript -e 'tell app "System Events" to display alert "UnrealEditor을(를) 추출하는데 실패하였습니다."'
             logcat_append "UnrealEditor does not ejected successfully. Please see the output above."
             logcat_append "Unable to eject UnrealEditor.dmg disk image due to EpicGameLauncher and UnrealEditor is still running."
-            logcat_append "UnrealLauncher exited at $(date).\n"
-            exit 1
+            cleanup_process 1
         else
-            logcat_append "UnrealLauncher exited at $(date).\n"
-            exit 0
+            cleanup_process 0
         fi
     else
         sleep 1
