실행 로그 처리방식 변경

diff --git a/Operating System/macOS/Public/UnrealLauncher.app/Contents/MacOS/UnrealLauncher b/Operating System/macOS/Public/UnrealLauncher.app/Contents/MacOS/UnrealLauncher
--- a/Operating System/macOS/Public/UnrealLauncher.app/Contents/MacOS/UnrealLauncher
+++ b/Operating System/macOS/Public/UnrealLauncher.app/Contents/MacOS/UnrealLauncher
@@ -3,7 +3,8 @@
 debugOutput=~/Library/Logs/Unreal\ Engine/UnrealLauncher/launch.log
 
 if [ -d ~/Library/Logs/Unreal\ Engine/UnrealLauncher ]; then
-    echo "log directory already exists." > "$debugOutput"
+    echo "UnrealLauncher was started at $(date)..." >> "$debugOutput"
+    echo "log directory already exists." >> "$debugOutput"
 else
     mkdir ~/Library/Logs/Unreal\ Engine/UnrealLauncher
     if [ $? != 0 ]; then
@@ -18,9 +19,11 @@ fi
 targetDir="$(echo $0 | sed "s/\/UnrealLauncher$//g")"
 cd "$targetDir" >> "$debugOutput" 2>&1
 if [ $? != 0 ]; then
+    echo -e "Unable to locate $targetDir. Aborting.\n" >> "$debugOutput"
     osascript -e 'tell app "System Events" to display alert "프로그램 현재 위치에 접근할 수 없어 실행할 수 없습니다. "'
     exit 1
 else
+    echo -n "Current working directory: " >> "$debugOutput"
     pwd >> "$debugOutput" 2>&1
 fi
 
@@ -31,12 +34,12 @@ elif [ -d /Volumes/External -a -r /Volumes/External/Applications/Epic\ Games/Unr
         open /Volumes/External/Applications/Epic\ Games/UnrealEditor.dmg >> "$debugOutput" 2>&1
         echo "Successfully mount /Volumes/External/Applications/Epic Games/UnrealEditor.dmg disk image." >> "$debugOutput"
     else
-        echo "Unable to mount /Volumes/External/Applications/Epic Games/UnrealEditor.dmg disk image. Please check your permission." >> "$debugOutput"
+        echo -e "Unable to mount /Volumes/External/Applications/Epic Games/UnrealEditor.dmg disk image. Please check your permission.\n" >> "$debugOutput"
         osascript -e 'tell app "System Events" to display alert "UnrealEditor을(를) 마운트 할 수 없습니다. 디스크 쓰기 권한을 확인해 주세요."'
         exit 1
     fi
 else
-    echo "Unable to locate UnrealEditor.dmg. Exiting." >> "$debugOutput"
+    echo -e "Unable to locate UnrealEditor.dmg. Exiting.\n" >> "$debugOutput"
     osascript -e 'tell app "System Events" to display alert "External 디스크가 감지되지 않아 UnrealEditor을(를) 마운트할 수 없습니다."'
     exit 1
 fi
@@ -45,10 +48,17 @@ if [ -x /Applications/Epic\ Games\ Launcher.app ]; then
     open /Applications/Epic\ Games\ Launcher.app >> "$debugOutput" 2>&1
     echo "Succesfully launched Epic Games Launcher.app." >> "$debugOutput"
 else
-    echo "Unable to execute Epic Games Launcher.app: no such file or directory." >> "$debugOutput"
+    echo -e "Unable to execute Epic Games Launcher.app: no such file or directory.\n" >> "$debugOutput"
+    exit 1
 fi
 
 while : ; do
+    logSize=$(ls -l ~/Library/Logs/Unreal\ Engine/UnrealLauncher/launch.log | awk '{ print $5 }')
+    if [ $logSize -ge 1000000 ]; then
+        echo "The log file content reached maximum log file size (1MB)." > "$debugOutput"
+        echo -e "Removed previous log file contents...\n" >> "$debugOutput"
+    fi
+
     pgrep EpicGamesLauncher &> /dev/null
     if [ $? == 0 ]; then
         echo "EpicGamesLauncher is running! PID: $(pgrep EpicGamesLauncher)" >> "$debugOutput"
@@ -73,7 +83,11 @@ while : ; do
         diskutil eject $(df -h | grep UnrealEditor | awk '{ print $1 }') >> "$debugOutput" 2>&1
         if [ $? != 0 ]; then
             osascript -e 'tell app "System Events" to display alert "UnrealEditor을(를) 추출하는데 실패하였습니다."'
+            echo "UnrealEditor does not ejected successfully. Please see the output above." >> "$debugOutput"
+            echo -e "UnrealLauncher exited at $(date).\n" >> "$debugOutput"
+            exit 1
         else
+            echo -e "UnrealLauncher exited at $(date).\n" >> "$debugOutput"
             exit 0
         fi
     else
