UnrealLauncher 종료 요청 기능 추가

diff --git a/Operating System/macOS/Public/UnrealLauncher.app/Contents/MacOS/UnrealLauncher b/Operating System/macOS/Public/UnrealLauncher.app/Contents/MacOS/UnrealLauncher
--- a/Operating System/macOS/Public/UnrealLauncher.app/Contents/MacOS/UnrealLauncher
+++ b/Operating System/macOS/Public/UnrealLauncher.app/Contents/MacOS/UnrealLauncher
@@ -54,7 +54,10 @@ if [ -r /Library/Application\ Support/Epic/UnrealLauncher/newagent.lock ]; then
     launchedUser=$(ls -l /Library/Application\ Support/Epic/UnrealLauncher/newagent.lock | awk '{ print $3 }')
     if [ "$USER" != "$launchedUser" ]; then
         echo "error: Unable to launch new agent. Someone already running this app."
-        osascript -e "display alert \"$launchedUser 사용자가 UnrealLauncher를 사용하고 있기 때문에 계속할 수 없습니다.\" as critical"
+        osascript -e "display alert \"이미 다른 사용자가 UnrealLauncher를 사용하고 있습니다.\" message \"Epic Games Launcher를 계속 사용하려면 $launchedUser 에게 관련된 앱을 모두 종료해 달라고 요청하십시오.\" as critical buttons {\"승인\",\"요청\"} default button \"요청\" cancel button \"승인\"" > /dev/null 2>&1
+        if [ $? == 0 ]; then
+            touch /Library/Application\ Support/Epic/UnrealLauncher/checkinfo
+        fi
     else
         echo "error: Unable to launch new agent. This app already running."
         osascript -e 'display alert "UnrealLauncher이(가) 이미 실행중입니다." as critical'
@@ -170,6 +173,18 @@ while : ; do
     if (( $(echo "$cntLoadAverages > $deviceCPUCount*2" | bc -l) )); then
         logcat_append "$(uname -n) is throttled. UnrealLauncher was limited operation due to inviolate UnrealEditor performance."
         sleep 15
+    fi
+
+    if [ -r /Library/Application\ Support/Epic/UnrealLauncher/checkinfo ]; then
+        requestUser=$(ls -l /Library/Application\ Support/Epic/UnrealLauncher/checkinfo | awk '{ print $3 }')
+        logcat_append "detected new agent requested term file from $requestUser at $(date)."
+        osascript -e "display notification \"$requestUser 사용자가 UnrealLauncher 실행을 원하고 있습니다. \" with title \"UnrealLauncher 실행 요청\""
+        rm -f /Library/Application\ Support/Epic/UnrealLauncher/checkinfo 2> /dev/null
+        if [ $? == 0 ]; then
+            logcat_append "Successfully deleted new agent request term file."
+        else
+            logcat_append "Unable to delete new agent request term file."
+        fi
     fi
 
     pgrep EpicGamesLauncher &> /dev/null
