종료시 클린업 기능 추가 및 코드 최적화

diff --git a/Operating System/Windows/WSL/KakaoTalkLauncher b/Operating System/Windows/WSL/KakaoTalkLauncher
--- a/Operating System/Windows/WSL/KakaoTalkLauncher
+++ b/Operating System/Windows/WSL/KakaoTalkLauncher
@@ -4,27 +4,59 @@ which open > /dev/null
 if [ $? != 0 ]; then
     exit 1
 fi
-
-echo -n "Launching KakaoTalkAdBlock application ... "
-if [ -r "/mnt/c/Users/$USER/AppData/Roaming/Microsoft/Windows/Start Menu/Programs/KakaoTalkAdBlock/KakaoTalkAdBlock.appref-ms" ]; then
-    open "/mnt/c/Users/$USER/AppData/Roaming/Microsoft/Windows/Start Menu/Programs/KakaoTalkAdBlock/KakaoTalkAdBlock.appref-ms" &
-else
-    echo -e "\nUnable to locate KakaoTalkAdBlock."
-    open "https://github.com/blurfx/KakaoTalkAdBlock"
+which taskkill.exe > /dev/null
+if [ $? != 0 ]; then
     exit 1
 fi
 
-sleep 5
-echo "Done."
+echo -n "Launching KakaoTalkAdBlock application ... "
+if [ -r "/mnt/c/Users/$USER/AppData/Roaming/Microsoft/Windows/Start Menu/Programs/KakaoTalkAdBlock/KakaoTalkAdBlock.appref-ms" ]; then
+    KakaoTalkAdBlockPID=$(powershell.exe -Command '(Get-Process KakaoTalkAdBlock).id' 2> /dev/null)
+    if [ "$KakaoTalkPID" != "" ]; then
+        taskkill.exe -F -IM KakaoTalkAdBlock.exe &> /dev/null
+    fi
+    sleep 1
+    open "/mnt/c/Users/$USER/AppData/Roaming/Microsoft/Windows/Start Menu/Programs/KakaoTalkAdBlock/KakaoTalkAdBlock.appref-ms" &
+    if [ $? != 0 ]; then
+        echo -e "\nUnable to launch KakaoTalkAdBlock. Please check permission. Aborting." >&2
+        exit 1
+    else
+        sleep 5
+        echo "Done."
+    fi
+else
+    echo -e "\nUnable to locate KakaoTalkAdBlock." >&2
+    open "https://github.com/blurfx/KakaoTalkAdBlock"
+    exit 1
+fi
 
 echo -n "Launching KakaoTalk application ... "
 if [ -r "/mnt/c/Program Files (x86)/Kakao/KakaoTalk/KakaoTalk.exe" ]; then
     open "/mnt/c/Program Files (x86)/Kakao/KakaoTalk/KakaoTalk.exe"
     echo "Done."
-    exit 0
 else
-    echo -e "\nUnable to locate KakaoTalk."
+    echo -e "\nUnable to locate KakaoTalk." >&2
+    KakaoTalkAdBlockPID=$(powershell.exe -Command '(Get-Process KakaoTalkAdBlock).id' 2> /dev/null)
+    if [ "$KakaoTalkPID" != "" ]; then
+        taskkill.exe -F -IM KakaoTalkAdBlock.exe &> /dev/null
+    fi
     open "https://kakao.io/?lang=KR"
     exit 1
 fi
+
+echo -n "Waiting untill KakaoTalk application exited ... "
+while true; do
+    KakaoTalkPID=$(powershell.exe -Command '(Get-Process KakaoTalk).id' 2> /dev/null)
+    if [ x"$KakaoTalkPID" == x ]; then
+        taskkill.exe -F -IM KakaoTalkAdBlock.exe > /dev/null
+        if [ $? != 0 ]; then
+            echo -e "\nUnable to terminate KakaoTalkAdBlock. Please exit KakaoTalkAdBlock manually." >&2
+            exit 1
+        else
+            echo "Done."
+            exit 0
+        fi
+    fi
+    sleep 1
+done
 
