대기 후에도 PID를 찾을 수 없을 경우 입력 요청

diff --git a/Operating System/Windows/WSL/KakaoTalkLauncher b/Operating System/Windows/WSL/KakaoTalkLauncher
--- a/Operating System/Windows/WSL/KakaoTalkLauncher
+++ b/Operating System/Windows/WSL/KakaoTalkLauncher
@@ -21,7 +21,7 @@ fi
 echo -n "Launching KakaoTalkAdBlock application ... "
 if [ -r "/mnt/c/Users/$USER/AppData/Roaming/Microsoft/Windows/Start Menu/Programs/KakaoTalkAdBlock/KakaoTalkAdBlock.appref-ms" ]; then
     KakaoTalkAdBlockPID=$(powershell.exe -Command '(Get-Process KakaoTalkAdBlock).id' 2> /dev/null)
-    if [ "$KakaoTalkPID" != "" ]; then
+    if [ "$KakaoTalkAdBlockPID" != "" ]; then
         taskkill.exe -F -IM KakaoTalkAdBlock.exe &> /dev/null
     fi
     sleep 1
@@ -49,7 +49,7 @@ else
     powershell.exe '(New-Object -ComObject Wscript.Shell).Popup("Unable to locate KakaoTalk.",0,"KakaoTalkLauncher",0x10)' &> /dev/null
     echo -e "\nUnable to locate KakaoTalk." >&2
     KakaoTalkAdBlockPID=$(powershell.exe -Command '(Get-Process KakaoTalkAdBlock).id' 2> /dev/null)
-    if [ "$KakaoTalkPID" != "" ]; then
+    if [ "$KakaoTalkAdBlockPID" != "" ]; then
         taskkill.exe -F -IM KakaoTalkAdBlock.exe &> /dev/null
     fi
     open "https://kakao.io/?lang=KR"
@@ -65,9 +65,7 @@ while true; do
             respond=$(powershell.exe '(New-Object -ComObject Wscript.Shell).Popup("Unable to find KakaoTalk process.`n`nPlease choose after progress...`nAbort:`tTerminate KakaoTalkAdBlock and exit.`nRetry:`tWait for a moment when KakaoTalk relaunches.`nIgnore:`tJust exit this script.",0,"KakaoTalkLauncher",0x22)' 2> /dev/null | tr -d '\r')
 
             if [ $respond -eq 3 ]; then
-                CurrentElapsedTime=$ExitDelaySeconds
-            elif [ $respond -eq 4 ]; then
-                echo "" &> /dev/null
+                CurrentElapsedTime=$(($ExitDelaySeconds*2))
             elif [ $respond -eq 5 ]; then
                 respond=$(powershell.exe '(New-Object -ComObject Wscript.Shell).Popup("Would you like ignore KakaoTalkAdBlock process?`nYou can exit KakaoTalkAdBlock manually.",0,"KakaoTalkLauncher",0x34)' 2> /dev/null | tr -d '\r')
                 if [ $respond -eq 7 ]; then
@@ -84,6 +82,19 @@ while true; do
             sleep 1
             CurrentElapsedTime=$(($CurrentElapsedTime+1))
             continue
+        fi
+
+        if [ $CurrentElapsedTime -eq $ExitDelaySeconds ]; then
+            respond=$(powershell.exe '(New-Object -ComObject Wscript.Shell).Popup("KakaoTalk did not launched yet.`nWould you like to launch KakaoTalk? If not, script will exit immediately.",0,"KakaoTalkLauncher",0x24)' 2> /dev/null | tr -d '\r')
+            if [ $respond -eq 6 ]; then
+                open "/mnt/c/Program Files (x86)/Kakao/KakaoTalk/KakaoTalk.exe"
+                if [ $? != 0 ]; then
+                    powershell.exe '(New-Object -ComObject Wscript.Shell).Popup("Unable to locate KakaoTalk.",0,"KakaoTalkLauncher",0x10)' &> /dev/null
+                    echo -e "\nUnable to locate KakaoTalk." >&2
+                else
+                    continue
+                fi
+            fi
         fi
 
         taskkill.exe -F -IM KakaoTalkAdBlock.exe > /dev/null
