마이너 버그 수정

diff --git a/Operating System/Linux/General/Build native Linux UnrealEditor b/Operating System/Linux/General/Build native Linux UnrealEditor
--- a/Operating System/Linux/General/Build native Linux UnrealEditor
+++ b/Operating System/Linux/General/Build native Linux UnrealEditor
@@ -62,12 +62,13 @@ elif [ "$1" == "channel" -o "$1" == "--channel" ]; then
         echo "current branch and provided branch are identical" >&2
         exit 1
     else
-        git diff HEAD...origin/$n 2> /dev/null
+        git --no-pager branch -r | sed "s/origin\///g" | grep "$n" &> /dev/null
         if [ $? -ne 0 ]; then
-            echo "unknown branch name: $n" >&2
+            echo "unknown branch name $n. Aborted" >&2
             exit 1
         fi
 
+        git diff HEAD...origin/$n
         echo -e "\e[33mWarning\e[m: If you want to change UnrealEditor branch, you should rebuild UnrealEditor changes effect. This action can not be undo."
         echo -n "Are you sure continue this action? (y/N) > "
         read cn
