UnrealEditor 레포 정리작업 추가

diff --git a/Operating System/Linux/General/Build native Linux UnrealEditor b/Operating System/Linux/General/Build native Linux UnrealEditor
--- a/Operating System/Linux/General/Build native Linux UnrealEditor
+++ b/Operating System/Linux/General/Build native Linux UnrealEditor
@@ -184,6 +184,11 @@ if [ $? -ne 0 ]; then
     echo "unable to update UnrealEngine repository. try again later." >&2
     exit 1
 fi
+git gc --prune=now
+if [ $? -ne 0 ]; then
+    echo "unable to clean-up UnrealEngine repository. try again later." >&2
+    exit 1
+fi
 
 echo "Generating project files..."
 
