브랜치 변경 기능 추가

diff --git a/Operating System/Linux/General/Build native Linux UnrealEditor b/Operating System/Linux/General/Build native Linux UnrealEditor
--- a/Operating System/Linux/General/Build native Linux UnrealEditor
+++ b/Operating System/Linux/General/Build native Linux UnrealEditor
@@ -6,8 +6,9 @@ if [ "$1" == "help" -o "$1" == "--help" ]; then
     echo "usage: $0 [option] [build-options [build-options1.2..]] [build-preset]"
     echo ""
     echo "OPTIONS"
-    echo -e "  help\t Show this manual"
-    echo -e "  clean\t Delete caches and object files (UnrealEditor only)"
+    echo -e "  help\tShow this manual"
+    echo -e "  clean\tDelete caches and object files (UnrealEditor only)"
+    echo -e "channel\tShow current or change channel to use different UnrealEditor version."
     echo ""
     echo "SUPPORTED BUILD OPTIONS"
     echo "  CrashReportClient"
@@ -27,6 +28,41 @@ if [ "$1" == "help" -o "$1" == "--help" ]; then
     exit 0
 elif [ "$1" == "clean" -o "$1" == "--clean" ]; then
     shouldProjectClean=1
+elif [ "$1" == "channel" -o "$1" == "--channel" ]; then
+    if [ x"$UEPath" == x -o ! -d "$UEPath/.git" ]; then
+        echo "unable to locate UnrealEditor. please provide absolute path." >&2
+        exit 1
+    elif [ ! -x "$UEPath/Setup.sh" ]; then
+        echo "UnrealEngine directory structure does not seem here." >&2
+        echo "$UEPath" >&2
+        echo "before use this change channel function, you should execute this cript without any parameters once."
+        exit 1
+    fi
+
+    cd "$UEPath"
+    if [ $? -ne 0 ]; then
+        exit 1
+    fi
+    git remote update
+    git --no-pager branch -r | sed "s/origin\///g" | grep -v "dev" | grep -v "stag" | grep -v "test" | grep -v "HEAD"
+    echo "current branch: $(git branch --show-current)"
+    echo -n "new branch name: "
+    read n
+    if [ x"$n" == x ]; then
+        echo "User abort." >&2
+        exit 1
+    elif [ "$(git branch --show-current)" == "$n" ]; then
+        echo "current branch and provided branch are identical" >&2
+        exit 1
+    else
+        git checkout -t origin/$n
+        if [ $? -ne 0 ]; then
+            echo "unable to change branch $n."
+        else
+            echo "successfully to change branch $n. you will need to execute this script again to building UnrealEditor."
+        fi
+        exit $?
+    fi
 fi
 
 echo "Checking dependency..."
