UnrealEditor 환경변수를 알리도록 수정

diff --git a/Operating System/Linux/General/Build native Linux UnrealEditor b/Operating System/Linux/General/Build native Linux UnrealEditor
--- a/Operating System/Linux/General/Build native Linux UnrealEditor
+++ b/Operating System/Linux/General/Build native Linux UnrealEditor
@@ -110,12 +110,14 @@ clang --version
 cmake --version
 
 if [ x"$UEPath" == x ]; then
-    echo "unable to locate UnrealEditor. please provide absolute path." >&2
+    echo "unable to locate UnrealEditor. please set UEPath with absolute path." >&2
     exit 1
 elif [ ! -x "$UEPath/Setup.sh" ]; then
     echo "UnrealEngine directory structure does not seem here." >&2
-    echo "$UEPath" >&2
+    echo "UEPath: $UEPath"
     exit 1
+else
+    echo "UEPath: $UEPath"
 fi
 
 if [ ! -r "$UEPath/.DS_Store" ]; then
diff --git a/Operating System/Linux/General/Launch UnrealEditor b/Operating System/Linux/General/Launch UnrealEditor
--- a/Operating System/Linux/General/Launch UnrealEditor
+++ b/Operating System/Linux/General/Launch UnrealEditor
@@ -68,8 +68,10 @@ function LaunchUnrealEditor() {
 }
 
 if [ x"$UEPath" == x -o ! -d "$UEPath/.git" ]; then
-    echo "unable to locate UnrealEditor. please provide absolute path." >&2
+    echo "unable to locate UnrealEditor. please set UEPath with absolute path." >&2
     CloseTerminalDelay 3 1
+else
+    echo "UEPath: $UEPath"
 fi
 
 cd "$UEPath"
