`docker volume rm` 기능 추가

diff --git a/Operating System/Linux/General/docker-purge b/Operating System/Linux/General/docker-purge
--- a/Operating System/Linux/General/docker-purge
+++ b/Operating System/Linux/General/docker-purge
@@ -2,6 +2,7 @@
 
 container=
 image=
+volume=
 
 function permission_check() {
     id | grep docker &> /dev/null
@@ -24,8 +25,9 @@ function permission_check() {
 if [ $# -eq 2 ]; then
     container=$1
     image=$2
+    volume=$3
 elif [ "$1" == "help" -o "$1" == "--help" ]; then
-    echo "usage: $0 [option | container image]"
+    echo "usage: $0 [option | container image volume]"
     echo -e "--help\tShow this help and exit."
     exit 0
 else
@@ -40,7 +42,12 @@ else
     echo -n "image ID: "
     read n
     image="$n"
-    if [ x"$image" == x -a x"$container" == x ]; then
+
+    docker volume ls
+    echo -n "volume NAME: "
+    read n
+    image="$n"
+    if [ x"$image" == x -a x"$container" == x ] && [ x"$volume" == x ]; then
         echo "User Abort." >&2
         exit 1
     fi
@@ -67,6 +74,14 @@ if ! [ x"$image" == x ]; then
     fi
 fi
 
+if ! [ x"$volume" == x ]; then
+    docker volume inspect $volume &> /dev/null
+    if [ $? -ne 0 ]; then
+        echo "error: no such volume: $volume" >&2
+        exit 1
+    fi
+fi
+
 permission_check
 if ! [ x"$container" == x ]; then
     docker top $container &>/dev/null
@@ -78,4 +93,8 @@ fi
 
 if ! [ x"$image" == x ]; then
     docker rmi $image
+fi
+
+if ! [ x"$volume" == x ]; then
+    docker volume rm $volume
 fi
