마이너 버그 수정

diff --git a/Operating System/Linux/General/docker-init b/Operating System/Linux/General/docker-init
--- a/Operating System/Linux/General/docker-init
+++ b/Operating System/Linux/General/docker-init
@@ -19,45 +19,52 @@ elif [ "$1" == "help" -o "$1" == "--help" ]; then
     exit 0
 else
     permission_check
-    docker container ls
+    docker ps -a
 
     echo -n "container ID or NAME: "
     read n
     container=$n
-    if [ x$n == x ]; then
-        echo "User Abort." >&2
-        exit 1
-    fi
 
+    docker images
     echo -n "image ID or NAME: "
     read n
-    if [ x$n == x ]; then
+    if [ x$n == x -a x$container == x ]; then
         echo "User Abort." >&2
         exit 1
     fi
     image=$n
+    echo ""
 fi
 
-docker container inspect $container &> /dev/null
-if [ $? -ne 0 ]; then
-    echo "error: no such container: $container" >&2
-    exit 1
-else
-    docker container logs $container
+if ! [ x$container == x ]; then
+    docker container inspect $container &> /dev/null
+    if [ $? -ne 0 ]; then
+        echo "error: no such container: $container" >&2
+        exit 1
+    else
+        docker container logs $container
+    fi
 fi
 
-docker image inspect $image &> /dev/null
-if [ $? -ne 0 ]; then
-    echo "error: no such image: $image" >&2
-    exit 1
-else
-    docker image history $image
+if ! [ x$image == x ]; then
+    docker image inspect $image &> /dev/null
+    if [ $? -ne 0 ]; then
+        echo "error: no such image: $image" >&2
+        exit 1
+    else
+        docker image history $image
+    fi
 fi
 
 permission_check
-docker top $container &>/dev/null
-if [ $? -eq 0 ]; then
-    docker stop $container
+if ! [ x$container == x ]; then
+    docker top $container &>/dev/null
+    if [ $? -eq 0 ]; then
+        docker stop $container
+    fi
+    docker rm $container
 fi
-docker rm $container
-docker rm $image
+
+if ! [ x$image == x ]; then
+    docker rmi $image
+fi
