Windows pip를 업데이트 리스트에 추가

diff --git a/Operating System/Linux/General/extension b/Operating System/Linux/General/extension
--- a/Operating System/Linux/General/extension
+++ b/Operating System/Linux/General/extension
@@ -23,6 +23,19 @@ if [ $? == 0 ]; then
     fi
 fi
 
+which pip3.exe &> /dev/null
+if [ $? == 0 ]; then
+    pip3.exe list --format=freeze | awk -F"==" '{print $1}' | xargs -i pip3.exe install -U {}
+    if [ $? != 0 ]; then
+        if [ $LANG == "ko_KR.UTF-8" ]; then
+            echo "pip3.exe 을 업데이트 하는 도중 에러가 발생하였습니다. "
+        else
+            echo "An error occured when updating pip3.exe."
+        fi
+        errorCount=$((errorCount+1))
+    fi
+fi
+
 do-release-upgrade
 if [ $? != 0 ]; then
     errorCount=$((errorCount+1))
