IP 주소 필터링 세분화

diff --git a/Operating System/Linux/General/inet-addr b/Operating System/Linux/General/inet-addr
--- a/Operating System/Linux/General/inet-addr
+++ b/Operating System/Linux/General/inet-addr
@@ -16,7 +16,9 @@ if [ "$1" == "--help" ]; then
 fi
 
 function mask_addr() {
-    if [ $1 -eq 1 ]; then
+    if [ $1 -eq 0 ]; then
+        echo "$2"
+    elif [ $1 -eq 1 ]; then
         printf '♡.%s.%s.%s\n' $(echo $2 | awk -F. '{ print $2 }') $(echo $2 | awk -F. '{ print $3 }') $(echo $2 | awk -F. '{ print $4 }')
     elif [ $1 -eq 2 ]; then
         printf '%s.♡.%s.%s\n' $(echo $2 | awk -F. '{ print $1 }') $(echo $2 | awk -F. '{ print $3 }') $(echo $2 | awk -F. '{ print $4 }')
@@ -28,7 +30,7 @@ function mask_addr() {
         echo "$2"
 
         if [ $mask -gt 4 -o $mask -lt 0 ]; then
-            echo "error: index out of bounds. 1...4 <> $mask" >&2
+            echo "error: index out of bounds. 0...4 <> $mask" >&2
             echo "IPv4 address mask function fault." >&2
         fi
 
@@ -56,6 +58,21 @@ for i in "${params[@]}"; do
     "--mask=4")
         mask=4
         ;;
+    "--mask=01")
+        mask=-1
+        ;;
+    "--mask=02")
+        mask=-2
+        ;;
+    "--mask=03")
+        mask=-3
+        ;;
+    "--mask=04")
+        mask=-4
+        ;;
+    "--mask=10")
+        mask=10
+        ;;
     "--mask=12")
         mask=12
         ;;
@@ -64,6 +81,9 @@ for i in "${params[@]}"; do
         ;;
     "--mask=14")
         mask=14
+        ;;
+    "--mask=20")
+        mask=20
         ;;
     "--mask=21")
         mask=21
@@ -74,6 +94,9 @@ for i in "${params[@]}"; do
     "--mask=24")
         mask=24
         ;;
+    "--mask=30")
+        mask=30
+        ;;
     "--mask=31")
         mask=31
         ;;
@@ -82,6 +105,9 @@ for i in "${params[@]}"; do
         ;;
     "--mask=34")
         mask=34
+        ;;
+    "--mask=40")
+        mask=40
         ;;
     "--mask=41")
         mask=41
@@ -128,7 +154,22 @@ elif [ $addr_mode -eq 2 ]; then
     mask_public=$mask
     mask_private=$mask
 
-    if [ $mask -eq 12 ]; then
+    if [ $mask -eq -1 ]; then
+        mask_public=0
+        mask_private=1
+    elif [ $mask -eq -2 ]; then
+        mask_public=0
+        mask_private=2
+    elif [ $mask -eq -3 ]; then
+        mask_public=0
+        mask_private=3
+    elif [ $mask -eq -4 ]; then
+        mask_public=0
+        mask_private=4
+    elif [ $mask -eq 10 ]; then
+        mask_public=1
+        mask_private=0
+    elif [ $mask -eq 12 ]; then
         mask_public=1
         mask_private=2
     elif [ $mask -eq 13 ]; then
@@ -137,6 +178,9 @@ elif [ $addr_mode -eq 2 ]; then
     elif [ $mask -eq 14 ]; then
         mask_public=1
         mask_private=4
+    elif [ $mask -eq 20 ]; then
+        mask_public=2
+        mask_private=0
     elif [ $mask -eq 21 ]; then
         mask_public=2
         mask_private=1
@@ -146,6 +190,9 @@ elif [ $addr_mode -eq 2 ]; then
     elif [ $mask -eq 24 ]; then
         mask_public=2
         mask_private=4
+    elif [ $mask -eq 30 ]; then
+        mask_public=3
+        mask_private=0
     elif [ $mask -eq 31 ]; then
         mask_public=3
         mask_private=1
@@ -155,6 +202,9 @@ elif [ $addr_mode -eq 2 ]; then
     elif [ $mask -eq 34 ]; then
         mask_public=3
         mask_private=4
+    elif [ $mask -eq 40 ]; then
+        mask_public=4
+        mask_private=0
     elif [ $mask -eq 41 ]; then
         mask_public=4
         mask_private=1
