IP를 한번에 표시할 때 위치를 달리 마스킹할 수 있도록 변경

diff --git a/Operating System/Linux/General/inet-addr b/Operating System/Linux/General/inet-addr
--- a/Operating System/Linux/General/inet-addr
+++ b/Operating System/Linux/General/inet-addr
@@ -2,7 +2,7 @@
 
 addr_mode=0
 mask=0
-chk_url="https://raw.githubusercontent.com/HyeongminKim/ShellScript/master/Operating%20System/Linux/General/inet-addr"
+chk_url="ipinfo.io/ip"
 
 if [ "$1" == "--help" ]; then
     echo "$0 [options]"
@@ -10,6 +10,8 @@ if [ "$1" == "--help" ]; then
     echo -e " --public\tShow public IPv4 address (default: private)"
     echo -e " --all\t\tShow both IPv4 address if possable"
     echo -e " --mask=N\tMask N octet address (default: 2)"
+    echo -e " --mask=NM\tMask N address public & Mask M address private"
+    echo -e "\t\t\`--mask=NM\` option should using with \`--all\` options"
     exit 0
 fi
 
@@ -24,6 +26,12 @@ function mask_addr() {
         printf '%s.%s.%s.♡\n' $(echo $2 | awk -F. '{ print $1 }') $(echo $2 | awk -F. '{ print $2 }') $(echo $2 | awk -F. '{ print $3 }')
     else
         echo "$2"
+
+        if [ $mask -gt 4 -o $mask -lt 0 ]; then
+            echo "error: index out of bounds. 1...4 <> $mask" >&2
+            echo "IPv4 address mask function fault." >&2
+        fi
+
     fi
 }
 
@@ -48,6 +56,42 @@ for i in "${params[@]}"; do
     "--mask=4")
         mask=4
         ;;
+    "--mask=12")
+        mask=12
+        ;;
+    "--mask=13")
+        mask=13
+        ;;
+    "--mask=14")
+        mask=14
+        ;;
+    "--mask=21")
+        mask=21
+        ;;
+    "--mask=23")
+        mask=23
+        ;;
+    "--mask=24")
+        mask=24
+        ;;
+    "--mask=31")
+        mask=31
+        ;;
+    "--mask=32")
+        mask=32
+        ;;
+    "--mask=34")
+        mask=34
+        ;;
+    "--mask=41")
+        mask=41
+        ;;
+    "--mask=42")
+        mask=42
+        ;;
+    "--mask=43")
+        mask=43
+        ;;
     *)
         echo "unknown option: $i. Skipping." >&2
         ;;
@@ -55,7 +99,7 @@ for i in "${params[@]}"; do
 done
 
 if [ $addr_mode -eq 1 ]; then
-    cnt_ip="$(curl -s ipinfo.io/ip)"
+    cnt_ip="$(curl -s $chk_url)"
     echo -n 'Public: '
     mask_addr $mask $cnt_ip
 elif [ $addr_mode -eq 0 ]; then
@@ -66,7 +110,7 @@ elif [ $addr_mode -eq 0 ]; then
     fi
 
     cnt_ip=$(ifconfig $net_device | sed -n '2p' | awk '{ print $2 }')
-    diff_ip="$(curl -s ipinfo.io/ip)"
+    diff_ip="$(curl -s $chk_url)"
     if [ "$cnt_ip" == "$diff_ip" ]; then
         echo -n 'Public: '
         mask_addr $mask $cnt_ip
@@ -81,15 +125,56 @@ elif [ $addr_mode -eq 2 ]; then
         net_device="wlan0"
     fi
 
+    mask_public=$mask
+    mask_private=$mask
+
+    if [ $mask -eq 12 ]; then
+        mask_public=1
+        mask_private=2
+    elif [ $mask -eq 13 ]; then
+        mask_public=1
+        mask_private=3
+    elif [ $mask -eq 14 ]; then
+        mask_public=1
+        mask_private=4
+    elif [ $mask -eq 21 ]; then
+        mask_public=2
+        mask_private=1
+    elif [ $mask -eq 23 ]; then
+        mask_public=2
+        mask_private=3
+    elif [ $mask -eq 24 ]; then
+        mask_public=2
+        mask_private=4
+    elif [ $mask -eq 31 ]; then
+        mask_public=3
+        mask_private=1
+    elif [ $mask -eq 32 ]; then
+        mask_public=3
+        mask_private=2
+    elif [ $mask -eq 34 ]; then
+        mask_public=3
+        mask_private=4
+    elif [ $mask -eq 41 ]; then
+        mask_public=4
+        mask_private=1
+    elif [ $mask -eq 42 ]; then
+        mask_public=4
+        mask_private=2
+    elif [ $mask -eq 43 ]; then
+        mask_public=4
+        mask_private=3
+    fi
+
     cnt_ip=$(ifconfig $net_device | sed -n '2p' | awk '{ print $2 }')
-    diff_ip="$(curl -s ipinfo.io/ip)"
+    diff_ip="$(curl -s $chk_url)"
     if [ "$cnt_ip" == "$diff_ip" ]; then
         echo -n 'Public: '
-        mask_addr $mask $cnt_ip
+        mask_addr $mask_public $cnt_ip
     else
         echo -n 'Public: '
-        mask_addr $mask $diff_ip
+        mask_addr $mask_public $diff_ip
         echo -n 'Private: '
-        mask_addr $mask $cnt_ip
+        mask_addr $mask_private $cnt_ip
     fi
 fi
