레거시 인터페이스 명명규칙을 따르지 않을 경우 오류 메시지를 출력하도록 변경

diff --git a/Operating System/Linux/General/inet-addr b/Operating System/Linux/General/inet-addr
--- a/Operating System/Linux/General/inet-addr
+++ b/Operating System/Linux/General/inet-addr
@@ -3,6 +3,7 @@
 addr_mode=0
 mask=0
 chk_url="ipinfo.io/ip"
+net_device="eth0"
 
 if [ "$1" == "--help" ]; then
     echo "$0 [options]"
@@ -34,6 +35,19 @@ function mask_addr() {
             echo "IPv4 address mask function fault." >&2
         fi
 
+    fi
+}
+
+function net_device_select() {
+    ifconfig eth0 &>/dev/null
+    if [ $? -ne 0 ]; then
+        ifconfig wlan0 &>/dev/null
+        if [ $? -eq 0 ]; then
+            net_device="wlan0"
+        else
+            echo 'error: unknown network interface or device detected. please add below kernel params in your GRUB configuration.' >&2
+            echo "GRUB_CMDLINE_LINUX+='net.ifnames=0 biosdevname=0'" >&2
+        fi
     fi
 }
 
@@ -133,12 +147,7 @@ if [ $addr_mode -eq 1 ]; then
     echo -n 'Public: '
     mask_addr $mask $cnt_ip
 elif [ $addr_mode -eq 0 ]; then
-    net_device="eth0"
-    ifconfig eth0 &>/dev/null
-    if [ $? -ne 0 ]; then
-        net_device="wlan0"
-    fi
-
+    net_device_select
     cnt_ip=$(ifconfig $net_device | sed -n '2p' | awk '{ print $2 }')
     diff_ip="$(curl -s $chk_url)"
     if [ "$cnt_ip" == "$diff_ip" ]; then
@@ -149,11 +158,7 @@ elif [ $addr_mode -eq 0 ]; then
         mask_addr $mask $cnt_ip
     fi
 elif [ $addr_mode -eq 2 ]; then
-    net_device="eth0"
-    ifconfig eth0 &>/dev/null
-    if [ $? -ne 0 ]; then
-        net_device="wlan0"
-    fi
+    net_device_select
 
     mask_public=$mask
     mask_private=$mask
