핫리로드 기능 추가 및 코드 최적화

diff --git a/Operating System/Linux/General/Install CS8409 Sound Driver b/Operating System/Linux/General/Install CS8409 Sound Driver
--- a/Operating System/Linux/General/Install CS8409 Sound Driver
+++ b/Operating System/Linux/General/Install CS8409 Sound Driver
@@ -1,6 +1,7 @@
 #!/bin/bash
 
 trigger=0
+error=0
 
 if [ "$1" == "help" -o "$1" == "--help" ]; then
     echo "$0 [help|-y]"
@@ -32,12 +33,13 @@ fi
 
 echo "$(lsb_release -d | sed 's/Description:\t//'), kernel version: $(uname -r)"
 echo "NOTICE: You should install again if you upgrade kernel version."
-echo -e "\n*** REBOOT REQUIRED ***\n"
-echo -n "Do you want to continue setup CS8409 driver? (Y/n) > "
-read input
-if [ "$input" == "n" -o "$input" == "N" ]; then
-    echo "Abort." >&2
-    exit 1
+if [ $trigger -eq 0 ]; then
+    echo -n "Do you want to continue setup CS8409 driver? (Y/n) > "
+    read input
+    if [ "$input" == "n" -o "$input" == "N" ]; then
+        echo "Abort." >&2
+        exit 1
+    fi
 fi
 
 cd $HOME/snap/snd-hda-codec-cs8409
@@ -61,15 +63,33 @@ if [ $? -ne 0 ]; then
     exit $?
 fi
 
-echo "NOTICE: You should reboot your computer to changes take effect."
-if [ $trigger -eq 0 ]; then
+sudo depmod -Aa
+modinfo snd-hda-codec-cs8409
+if [ $? -ne 0 ]; then
+    echo "hot-reload was failed! no such modules about snd-hda-codec-cs8409" >&2
+    error=1
+fi
+sudo modprobe snd-hda-codec-cs8409
+if [ $? -ne 0 ]; then
+    echo "hot-reload was failed! unable to load snd-hda-codec-cs8409.ko" >&2
+    error=1
+fi
+lsmod | grep cs8409 &> /dev/null
+if [ $? -ne 0 ]; then
+    echo "hot-reload was failed! snd-hda-codec-cs8409 module did not loaded" >&2
+    error=1
+fi
+
+if [ $trigger -eq 0 -a $reboot -eq 1 ]; then
+    echo "NOTICE: You should reboot your computer to changes take effect."
     echo -n "Are you sure you want to reboot your computer now? (Y/n) > "
     read input
     if [ "$input" == "n" -o "$input" == "N" ]; then
-        echo "Please reboot your computer later."
+        echo "Please reboot your computer to changes take effect." >&2
     else
         sudo reboot
     fi
-else
-    echo "Please reboot your computer to changes take effect."
+elif [ $trigger -eq 1 -a $reboot -eq 1 ]; then
+    echo "Please reboot your computer to changes take effect." >&2
 fi
+
