이전 빌드 파일 정리과정 추가

diff --git a/Operating System/Linux/General/Install CS8409 Sound Driver b/Operating System/Linux/General/Install CS8409 Sound Driver
--- a/Operating System/Linux/General/Install CS8409 Sound Driver
+++ b/Operating System/Linux/General/Install CS8409 Sound Driver
@@ -25,6 +25,12 @@ fi
 
 cd $HOME/snap/snd-hda-codec-cs8409
 
+make clean
+if [ $? -ne 0 ]; then
+    echo "clean failed! exit code: $?. See above for output." >&2
+    exit $?
+fi
+
 make
 if [ $? -ne 0 ]; then
     echo "make failed! exit code: $?. See above for output." >&2
