설치 실패시 descriptor가 지정되지 않은 문제 수정

diff --git a/Operating System/Linux/General/Install CS8409 Sound Driver b/Operating System/Linux/General/Install CS8409 Sound Driver
--- a/Operating System/Linux/General/Install CS8409 Sound Driver
+++ b/Operating System/Linux/General/Install CS8409 Sound Driver
@@ -27,14 +27,14 @@ cd $HOME/snap/snd-hda-codec-cs8409
 
 make
 if [ $? -ne 0 ]; then
-    echo "make failed! exit code: $?. See above for output."
+    echo "make failed! exit code: $?. See above for output." >&2
     exit $?
 fi
 
 echo -e "\nTo install you should require admin permission."
 sudo make install
 if [ $? -ne 0 ]; then
-    echo "install failed! exit code: $?. See above for output."
+    echo "install failed! exit code: $?. See above for output." >&2
     exit $?
 fi
 
