CS8409 드라이버가 존재하지 않으면 사전에 알리도록 변경

diff --git a/Operating System/Linux/General/Install CS8409 Sound Driver b/Operating System/Linux/General/Install CS8409 Sound Driver
--- a/Operating System/Linux/General/Install CS8409 Sound Driver
+++ b/Operating System/Linux/General/Install CS8409 Sound Driver
@@ -1,7 +1,12 @@
 #!/bin/bash
 
 if [ ! -d $HOME/snap/snd-hda-codec-cs8409 ]; then
-    echo "cs8409: no such file or directory." >&2
+    echo -n "Would you like to download snd-hda-codec-cs8409 from github? (Y/n) > "
+    read n
+    if [ "$n" == "n" -o "$n" == "N" ]; then
+        echo "Abort." >&2
+        exit 1
+    fi
     echo "downloading sound driver: https://github.com/egorenar/snd-hda-codec-cs8409" >&2
     if [ ! -d $HOME/snap ]; then
         mkdir $HOME/snap
