코드 최적화

diff --git a/Operating System/Linux/General/mbpfan b/Operating System/Linux/General/mbpfan
--- a/Operating System/Linux/General/mbpfan
+++ b/Operating System/Linux/General/mbpfan
@@ -43,37 +43,66 @@ elif [ $# -eq 2 -a "$1" == "new" ]; then
         echo "error: $2 profile already exist." >&2
         exit 1
     fi
-    if [ $UID -ne 0 ]; then
-        sudo cp /etc/mbpfan.d/default /etc/mbpfan.d/$2
-        sudo vi /etc/mbpfan.d/$2
+    filename=/tmp/mbpfan-$(date +'%Y-%m-%d_%H:%M:%S')-$2
+    cp /etc/mbpfan.d/default $filename
+    vi $filename
+    cmp -s /etc/mbpfan.d/default $filename
+    if [ $? -eq 0 ]; then
+        echo "Aborting create $2 profile due to identical default profile." >&2
     else
-        cp /etc/mbpfan.d/default /etc/mbpfan.d/$2
-        vi /etc/mbpfan.d/$2
+        if [ $UID -ne 0 ]; then
+            sudo mv $filename /etc/mbpfan.d/$2
+        else
+            mv $filename /etc/mbpfan.d/$2
+        fi
+        echo "please re-run this script to apply $2 profile."
     fi
-    echo "please re-run this script to apply $2 profile."
+    rm $filename
 elif [ "$1" == "edit" ]; then
     if [ $# -eq 1 ]; then
-        if [ $UID -ne 0 ]; then
-            sudo vi /etc/mbpfan.d/$(basename `readlink /etc/mbpfan.conf`)
+        filename=/tmp/mbpfan-$(date +'%Y-%m-%d_%H:%M:%S')-$(basename `readlink /etc/mbpfan.conf`)
+        cp /etc/mbpfan.d/$(basename `readlink /etc/mbpfan.conf`) $filename
+        vi $filename
+        cmp -s /etc/mbpfan.d/$(basename `readlink /etc/mbpfan.conf`) $filename
+        if [ $? -eq 0 ]; then
+            echo "Aborting edit $(basename `readlink /etc/mbpfan.conf`) profile due to identical." >&2
         else
-            vi /etc/mbpfan.d/$(basename `readlink /etc/mbpfan.conf`)
+            if [ $UID -ne 0 ]; then
+                sudo mv -f $filename /etc/mbpfan.d/$(basename `readlink /etc/mbpfan.conf`)
+            else
+                mv -f $filename /etc/mbpfan.d/$(basename `readlink /etc/mbpfan.conf`)
+            fi
+            daemon-reload
         fi
+        rm $filename
     else
-        if [ $UID -ne 0 ]; then
-            sudo vi /etc/mbpfan.d/$2
+        filename=/tmp/mbpfan-$(date +'%Y-%m-%d_%H:%M:%S')-$2
+        cp /etc/mbpfan.d/$2 $filename
+        vi $filename
+        cmp -s /etc/mbpfan.d/$2 $filename
+        if [ $? -eq 0 ]; then
+            echo "Aborting edit $2 profile due to identical." >&2
+            exit 1
         else
-            vi /etc/mbpfan.d/$2
+            if [ $UID -ne 0 ]; then
+                sudo mv -f $filename /etc/mbpfan.d/$2
+            else
+                mv -f $filename /etc/mbpfan.d/$2
+            fi
+            daemon-reload
         fi
+        rm $filename
     fi
-    daemon-reload
 elif [ $# -eq 2 -a "$1" == "set" ]; then
     if [ -r /etc/mbpfan.d/$2 ]; then
+        prev_profile=$(basename `readlink /etc/mbpfan.conf`)
         if [ $UID -ne 0 ]; then
             sudo ln -sf /etc/mbpfan.d/$2 /etc/mbpfan.conf
         else
             ln -sf /etc/mbpfan.d/$2 /etc/mbpfan.conf
         fi
         daemon-reload
+        echo "profile changed $prev_profile to $2"
     else
         echo "error: no such profile: $2" >&2
     fi
