modified:   mbpfan

diff --git a/Operating System/Linux/General/mbpfan b/Operating System/Linux/General/mbpfan
--- a/Operating System/Linux/General/mbpfan
+++ b/Operating System/Linux/General/mbpfan
@@ -36,27 +36,52 @@ if [ $# -eq 0 -o "$1" == "status" ]; then
     echo "current_profile = $(basename `readlink /etc/mbpfan.conf`)"
     cat /etc/mbpfan.conf | grep '^m.._fan._speed =' | awk -F '#' '{ print $1 }'
     cat /etc/mbpfan.conf | grep 'temp =' | awk -F '#' '{ print $1 }'
-elif [ $# -eq 1 -a "$1" == "list" ]; then
+elif [ "$1" == "ls" -o "$1" == "list" ]; then
     ls /etc/mbpfan.d
 elif [ $# -eq 2 -a "$1" == "new" ]; then
-    if [ -r /etc/mbpfan.d/$2 ]; then
-        echo "error: $2 profile already exist." >&2
-        exit 1
-    fi
-
-    filename=/tmp/mbpfan-$(date +'%Y-%m-%d_%H:%M:%S')-$2
-    cp /etc/mbpfan.d/default $filename
-    vi $filename
-    cmp -s /etc/mbpfan.d/default $filename
-    if [ $? -eq 0 ]; then
-        echo "Aborting create $2 profile due to identical default profile." >&2
-    else
-        if [ $UID -ne 0 ]; then
-            sudo mv $filename /etc/mbpfan.d/$2
-        else
-            mv $filename /etc/mbpfan.d/$2
+    if [ $# -eq 2 ]; then
+        if [ -r /etc/mbpfan.d/$2 ]; then
+            echo "error: $2 profile already exist." >&2
+            exit 1
         fi
-        echo "please re-run this script to apply $2 profile."
+
+        filename=/tmp/mbpfan-$(date +'%Y-%m-%d_%H:%M:%S')-$2
+        cp /etc/mbpfan.d/default $filename
+        vi $filename
+        cmp -s /etc/mbpfan.d/default $filename
+        if [ $? -eq 0 ]; then
+            echo "Aborting create $2 profile due to identical default profile." >&2
+        else
+            if [ $UID -ne 0 ]; then
+                sudo mv $filename /etc/mbpfan.d/$2
+            else
+                mv $filename /etc/mbpfan.d/$2
+            fi
+            echo "please re-run this script to apply $2 profile."
+        fi
+    elif [ $# -eq 3 ]; then
+        if ! [ -r /etc/mbpfan.d/$2 ]; then
+            echo "error: no such profile: $2" >&2
+            exit 1
+        elif [ -r /etc/mbpfan.d/$3 ]; then
+            echo "error: $3 profile already exist." >&2
+            exit 1
+        fi
+
+        filename=/tmp/mbpfan-$(date +'%Y-%m-%d_%H:%M:%S')-$3
+        cp /etc/mbpfan.d/$2 $filename
+        vi $filename
+        cmp -s /etc/mbpfan.d/$2 $filename
+        if [ $? -eq 0 ]; then
+            echo "Aborting create $3 profile due to identical $2 profile." >&2
+        else
+            if [ $UID -ne 0 ]; then
+                sudo mv $filename /etc/mbpfan.d/$3
+            else
+                mv $filename /etc/mbpfan.d/$3
+            fi
+            echo "please re-run this script to apply $3 profile."
+        fi
     fi
 elif [ "$1" == "edit" ]; then
     if [ $# -eq 1 ]; then
@@ -75,20 +100,30 @@ elif [ "$1" == "edit" ]; then
             daemon-reload
         fi
     else
-        filename=/tmp/mbpfan-$(date +'%Y-%m-%d_%H:%M:%S')-$2
-        cp /etc/mbpfan.d/$2 $filename
-        vi $filename
-        cmp -s /etc/mbpfan.d/$2 $filename
-        if [ $? -eq 0 ]; then
-            echo "Aborting edit $2 profile due to identical." >&2
-            exit 1
-        else
-            if [ $UID -ne 0 ]; then
-                sudo mv -f $filename /etc/mbpfan.d/$2
-            else
-                mv -f $filename /etc/mbpfan.d/$2
+        target=("$@")
+        for i in "${!target[@]}"; do
+            if [ "${target[$i]}" == "edit" ]; then
+                continue
             fi
-        fi
+            if ! [ -r /etc/mbpfan.d/${target[$i]} ]; then
+                echo "error: no such profile: ${target[$i]}. Skipping" >&2
+                continue
+            fi
+
+            filename=/tmp/mbpfan-$(date +'%Y-%m-%d_%H:%M:%S')-${target[$i]}
+            cp /etc/mbpfan.d/${target[$i]} $filename
+            vi $filename
+            cmp -s /etc/mbpfan.d/${target[$i]} $filename
+            if [ $? -eq 0 ]; then
+                echo "Aborting edit ${target[$i]} profile due to identical." >&2
+            else
+                if [ $UID -ne 0 ]; then
+                    sudo mv -f $filename /etc/mbpfan.d/${target[$i]}
+                else
+                    mv -f $filename /etc/mbpfan.d/${target[$i]}
+                fi
+            fi
+        done
     fi
 elif [ $# -eq 2 -a "$1" == "set" ]; then
     if [ -r /etc/mbpfan.d/$2 ]; then
@@ -109,14 +144,38 @@ elif [ $# -eq 2 -a "$1" == "set" ]; then
         echo "error: no such profile: $2" >&2
         exit 1
     fi
-elif [ $# -eq 1 -a "$1" == "help" ]; then
+elif [ "$1" == "remove" -o "$1" == "rm" ]; then
+    prev_profile=$(basename `readlink /etc/mbpfan.conf`)
+    target=("$@")
+
+    for i in "${!target[@]}"; do
+        if [ "${target[$i]}" == "rm" -o "${target[$i]}" == "remove" ]; then
+            continue
+        fi
+        if ! [ -r /etc/mbpfan.d/${target[$i]} ]; then
+            echo "error: no such profile: ${target[$i]}. Skipping" >&2
+            continue
+        fi
+
+        if [ "$prev_profile" == "${target[$i]}" ]; then
+            echo "error: unable to remove provided profile in currently use. Skipping" >&2
+        else
+            if [ $UID -ne 0 ]; then
+                sudo rm /etc/mbpfan.d/${target[$i]}
+            else
+                rm /etc/mbpfan.d/${target[$i]}
+            fi
+        fi
+    done
+elif [ "$1" == "help" ]; then
     echo 'usage: mbpfan [option|profile]'
     echo -e '\nOPTIONS'
-    echo -e " list\t\tshow available profiles."
-    echo -e "  set <profile>\tupdate new profile for mbpfan."
-    echo -e "  new <name>\tcreate new profile."
-    echo -e " edit [name]\tedit specific or current profile."
-    echo -e " help\t\tshow this help."
+    echo -e "  list\t\t\t\tshow available profiles."
+    echo -e "   set <profile>\t\tupdate new profile for mbpfan."
+    echo -e "   new [source] <name>\t\tcreate new profile."
+    echo -e "  edit [name ...]\t\tedit specific or current profile."
+    echo -e "remove <name ...>\t\tdelete specific profile."
+    echo -e "  help\t\t\t\tshow this help."
     echo -e '\nAVAILABLE PROFILES'
     ls /etc/mbpfan.d
 else
