Intel turbo boost 토글 기능 추가

diff --git a/Operating System/Linux/General/mbpfan b/Operating System/Linux/General/mbpfan
--- a/Operating System/Linux/General/mbpfan
+++ b/Operating System/Linux/General/mbpfan
@@ -270,6 +270,32 @@ elif [ "$1" == "remove" -o "$1" == "rm" ]; then
             fi
         fi
     done
+elif [ "$1" == "turbo" ]; then
+    if [ $# -eq 1 -o "$2" == "status" ]; then
+        current_mode=$(cat /sys/devices/system/cpu/intel_pstate/no_turbo)
+        if [ $current_mode -eq 0 ]; then
+            echo 'turbo boost is enabled'
+        else
+            echo 'turbo boost is disabled'
+        fi
+    elif ! [ "$2" == "0" -o "$2" == "1" ]; then
+        echo "error: unknown parameter: $2" >&2
+        exit 1
+    else
+        if [ $2 -eq 1 ]; then
+            if [ $UID -ne 0 ]; then
+                echo 0 | sudo tee /sys/devices/system/cpu/intel_pstate/no_turbo > /dev/null
+            else
+                echo 0 > /sys/devices/system/cpu/intel_pstate/no_turbo
+            fi
+        else
+            if [ $UID -ne 0 ]; then
+                echo 1 | sudo tee /sys/devices/system/cpu/intel_pstate/no_turbo > /dev/null
+            else
+                echo 1 > /sys/devices/system/cpu/intel_pstate/no_turbo
+            fi
+        fi
+    fi
 elif [ "$1" == "help" ]; then
     echo 'usage: mbpfan [option]'
     echo -e '\nOPTIONS'
@@ -280,6 +306,7 @@ elif [ "$1" == "help" ]; then
     echo -e "    new [source] <name>\t\tcreate new profile."
     echo -e "   link [source] <name>\t\tlinking exist profile."
     echo -e "   edit [name ...]\t\tedit specific or current profile."
+    echo -e "  turbo [status|1|0]\t\t\tenable(1) or disable(0) Intel turbo boost."
     echo -e " remove <name ...>\t\tdelete specific profile."
     echo -e " rename [old] <new>\t\trename specific or current profile."
     echo -e "   help\t\t\t\tshow this help."
