무한 재시동에 빠질 수 있는 문제 수정

diff --git a/Operating System/Linux/General/network b/Operating System/Linux/General/network
--- a/Operating System/Linux/General/network
+++ b/Operating System/Linux/General/network
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+established=false
+
 if [ "$(uname)" != "Linux" ]; then
     echo "$(uname -srvmpio) is not supported. This script only works on Linux. " >&2
     exit 1
@@ -19,16 +21,26 @@ while true; do
     echo "Checking internet connection to www.google.com..."
     ping -c 1 -W 1 -q "www.google.com" &> /dev/null
     if [ $? != 0 ]; then
-        echo "No internet connection."
-        ifconfig $NET_TARGET_INTERFACE_UNIT down && ifconfig $NET_TARGET_INTERFACE_UNIT up
-        if [ $? != 0 ]; then
-            echo "fatal: Unable to reload $NET_TARGET_INTERFACE_UNIT network driver." >&2
-            echo -e "\tThis system will automatically reboot as soon as possible." >&2
-            sleep 2
-            reboot
+        if [ "$established" == "true" ]; then
+            echo "No internet connection."
+            ifconfig $NET_TARGET_INTERFACE_UNIT down && ifconfig $NET_TARGET_INTERFACE_UNIT up
+            if [ $? != 0 ]; then
+                echo "fatal: Unable to reload $NET_TARGET_INTERFACE_UNIT network driver." >&2
+                echo -e "\tThis system will automatically reboot as soon as possible." >&2
+                sleep 2
+                reboot
+            fi
+        else
+            echo "No internet connection. Waiting for establish connection..."
         fi
     else
-        echo "You have an internet connection."
+        if [ "$established" == "false" ]; then
+            echo "You have an internet connection."
+            echo "note: If your system disconnected the internet, this script will now attempt reload network driver."
+            established=true
+        else
+            echo "You have an internet connection."
+        fi
     fi
 
     sleep $(shuf -i 10-20 -n 1)
