systemctl 유닛 설치 위치 프리셋 기능 추가

diff --git a/Operating System/Linux/General/systemctl-install b/Operating System/Linux/General/systemctl-install
--- a/Operating System/Linux/General/systemctl-install
+++ b/Operating System/Linux/General/systemctl-install
@@ -20,6 +20,12 @@ if [ "$1" == "-h" -o "$1" == "--help" ]; then
     echo "- path"
     echo "- socket"
     echo "- timer"
+    echo ""
+    echo -e "DESTINATION\t\t\t\t\tPRI\tDEFAULT"
+    echo -e " 0, etc:\t/etc/systemd/system\t\t  5\t   *"
+    echo -e " 1, run:\t/run/systemd/system\t\t  0"
+    echo -e " 2, usr:\t/usr/lib/systemd/system\t\t-10"
+    echo -e " PATH\t\tcustom locations...\t\t 10"
     exit 0
 elif [ $# -lt 2 -o $# -gt 3 ]; then
     if [ $# -eq 0 ]; then
@@ -51,12 +57,25 @@ target_name=$(basename "$2")
 if [ $# -eq 2 ]; then
     echo "This script will create $target_name.$1 to /etc/systemd/system"
 elif [ $# -eq 3 ]; then
-    if ! [ -r "$3" ]; then
-        echo "systemd-inst: cannot access '$3': no such file or directory." >&2
-        exit 1
-    fi
+    case "$3" in
+        "0"|"etc")
+            inst_location=/etc/systemd/system
+        ;;
+        "1"|"run")
+            inst_location=/run/systemd/system
+        ;;
+        "2"|"usr")
+            inst_location=/usr/lib/systemd/system
+        ;;
+        *)
+            if ! [ -r "$3" ]; then
+                echo "systemd-inst: cannot access '$3': no such file or directory." >&2
+                exit 1
+            fi
 
-    inst_location=$(realpath "$3")
+            inst_location=$(realpath "$3")
+        ;;
+    esac
     echo "This script will create $target_name.$1 to $inst_location"
 fi
 
