SELinux 예외처리 추가

diff --git a/Operating System/Linux/General/systemctl-install b/Operating System/Linux/General/systemctl-install
--- a/Operating System/Linux/General/systemctl-install
+++ b/Operating System/Linux/General/systemctl-install
@@ -101,6 +101,20 @@ if ! [ "$n" == "Y" -o "$n" == "y" ]; then
     exit 1
 fi
 
+which getenforce &> /dev/null
+if [ $? -eq 0 ]; then
+    getenforce | grep Enforcing &> /dev/null
+    if [ $? -eq 0 ]; then
+        echo "Changing SELinux to Permissive mode"
+        sudo setenforce 0
+        if [ $? -ne 0 ]; then
+            echo "systemd-inst: error: could not install $target_name.$1 due to SELinux policy. Aborted." >&2
+            exit 1
+        fi
+        sestatus
+    fi
+fi
+
 echo -n "Please type description: "
 read desc
 
