대상 유닛파일이 이미 존재하는지 확인하는 기능 추가

diff --git a/Operating System/Linux/General/systemctl-install b/Operating System/Linux/General/systemctl-install
--- a/Operating System/Linux/General/systemctl-install
+++ b/Operating System/Linux/General/systemctl-install
@@ -59,6 +59,11 @@ if [ $# -eq 2 ]; then
     echo "This script will create $target_name.$1 to /etc/systemd/system"
     file "$target_path" 2> /dev/null
     xxd -l 64 "$target_path"
+
+    if [ -r /etc/systemd/system/$target_name.$1 ]; then
+        echo "systemd-inst: error: $target_name.$1 already exist in /etc/systemd/system" >&2
+        exit 1
+    fi
 elif [ $# -eq 3 ]; then
     case "$3" in
         "0"|"etc")
@@ -82,6 +87,11 @@ elif [ $# -eq 3 ]; then
     echo "This script will create $target_name.$1 to $inst_location"
     file "$target_path" 2> /dev/null
     xxd -l 64 "$target_path"
+
+    if [ -r /etc/systemd/system/$target_name.$1 ]; then
+        echo "systemd-inst: error: $target_name.$1 already exist in /etc/systemd/system" >&2
+        exit 1
+    fi
 fi
 
 echo -n "Are you wish to continue install $1? (y/N) > "
